# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40)),
                ('post_subject', models.CharField(max_length=100)),
                ('post_text', models.TextField()),
                ('post_datetime', models.DateTimeField()),
                ('post_season', models.CharField(choices=[('XC', 'XC'), ('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=10)),
            ],
        ),
    ]
