# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160711_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='distanceEvent',
            field=models.BooleanField(default=False),
        ),
    ]
