# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160705_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='meet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Meet'),
        ),
        migrations.AddField(
            model_name='result',
            name='result_membership',
            field=models.CharField(choices=[('Club', 'Club'), ('Alum', 'Alum'), ('Elite', 'Elite')], default='Club', max_length=6),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='membership',
            field=models.CharField(choices=[('Club', 'Club'), ('Alum', 'Alum'), ('Elite', 'Elite')], default='Club', max_length=10),
        ),
    ]
