# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160705_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Meet'),
        ),
    ]
