# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='relay_members',
            field=models.ManyToManyField(to='app.Athlete'),
        ),
    ]
